# Generated by Django 5.2.17 on 2026-08-27 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=180, unique=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('event_type', models.CharField(max_length=60)),
                ('payload_digest', models.CharField(max_length=64)),
                ('waba_id', models.CharField(max_length=120)),
                ('phone_number_id', models.CharField(max_length=120)),
                ('signature_valid', models.BooleanField(default=False)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module', models.CharField(default='pedidos', max_length=60)),
                ('source_type', models.CharField(default='shipment', max_length=60)),
                ('source_id', models.CharField(db_index=True, max_length=80)),
                ('order_visible_id', models.CharField(blank=True, max_length=160)),
                ('warehouse_reference', models.CharField(blank=True, max_length=160)),
                ('contact_reference', models.CharField(max_length=160)),
                ('recipient_name', models.CharField(max_length=160)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('rendered_body', models.TextField()),
                ('document_source_id', models.CharField(blank=True, max_length=80)),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('document_sha256', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], db_index=True, default='draft', max_length=24)),
                ('created_by', models.CharField(max_length=240)),
                ('approved_by', models.CharField(blank=True, max_length=240)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_module', 'source_type', 'source_id'], name='communicati_source__542c91_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=24)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('media_id', models.CharField(blank=True, max_length=180)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbox', to='communications.whatsappdraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('request_digest', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='communications.whatsappoutbox')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('outbox', 'sequence'), name='communications_whatsapp_attempt_sequence_unique')],
            },
        ),
    ]
