# Generated by Django 5.2.17 on 2026-08-17 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancePrototipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado')], default='activo', max_length=20)),
                ('ambiente', models.CharField(choices=[('desarrollo', 'Desarrollo'), ('staging', 'Staging'), ('produccion', 'Producción')], max_length=20)),
                ('url_github', models.URLField(blank=True, default='')),
                ('creado_por', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('merged_to_desarrollo', models.BooleanField(default=False)),
                ('merged_to_produccion', models.BooleanField(default=False)),
                ('url_merge_request', models.URLField(blank=True, default='')),
                ('github_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('ultima_actualizacion_webhook', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
