# Generated by Django 5.2.11 on 2026-08-20 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('app_label', models.CharField(max_length=100)),
                ('allow_concurrent', models.BooleanField(default=False)),
                ('max_concurrent_global', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de proceso',
                'verbose_name_plural': 'Tipos de proceso',
            },
        ),
        migrations.CreateModel(
            name='ProcessScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_kind', models.CharField(choices=[('ONCE_DATE', 'Fecha específica'), ('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('CRON', 'Expresión CRON')], max_length=20)),
                ('run_at_date', models.DateField(blank=True, null=True)),
                ('run_at_time', models.TimeField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='orchestrator.processtype')),
            ],
            options={
                'verbose_name': 'Programación de proceso',
                'verbose_name_plural': 'Programaciones de proceso',
            },
        ),
        migrations.CreateModel(
            name='ProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_COLA', 'En cola'), ('EJECUTANDO', 'Ejecutando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('CANCELANDO', 'Cancelando'), ('CANCELADO', 'Cancelado'), ('INTERRUMPIDO', 'Interrumpido')], default='PENDIENTE', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255, null=True)),
                ('logs', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('cancellation_requested', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_executions', to=settings.AUTH_USER_MODEL)),
                ('triggered_by_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='orchestrator.processscheduleconfig')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='orchestrator.processtype')),
            ],
            options={
                'verbose_name': 'Ejecución de proceso',
                'verbose_name_plural': 'Ejecuciones de proceso',
                'ordering': ['-created_at'],
            },
        ),
    ]
