# Generated by Django 5.2.17 on 2026-08-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='shopify_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
