# Generated by Django 5.2.17 on 2026-08-25 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_masterproduct_shopify_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='costobservation',
            name='derived_net_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='suppliercatalogitem',
            name='derived_net_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='SupplierCatalogImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=300)),
                ('source_path_at_import', models.TextField(blank=True)),
                ('source_sha256', models.CharField(max_length=64, unique=True)),
                ('catalog_date', models.DateField()),
                ('page_count', models.PositiveIntegerField()),
                ('extracted_rows', models.PositiveIntegerField()),
                ('unique_skus', models.PositiveIntegerField()),
                ('duplicate_skus', models.PositiveIntegerField(default=0)),
                ('invalid_prices', models.PositiveIntegerField(default=0)),
                ('missing_skus', models.PositiveIntegerField(default=0)),
                ('missing_descriptions', models.PositiveIntegerField(default=0)),
                ('exact_shopify_matches', models.PositiveIntegerField(default=0)),
                ('missing_shopify_matches', models.PositiveIntegerField(default=0)),
                ('ambiguous_shopify_matches', models.PositiveIntegerField(default=0)),
                ('tax_included_confirmed', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('audit_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_imports', to='catalogo.providerconfig')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
    ]
