# Generated by Django 5.2.17 on 2026-08-25 04:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_costobservation_derived_net_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basis', models.CharField(default='LOCAL_READ_ONLY', max_length=80)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='minimum_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='simulation_only',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='IntegrationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=40)),
                ('capability', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PARTIAL', 'Parcial'), ('MISSING', 'Dato ausente'), ('NOT_AUTHORIZED', 'No autorizado'), ('NOT_APPLICABLE', 'No aplica'), ('BLOCKED', 'Bloqueado')], max_length=24)),
                ('message', models.CharField(max_length=500)),
                ('evidence_reference', models.CharField(blank=True, max_length=300)),
                ('record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['system', 'capability'],
                'constraints': [models.UniqueConstraint(fields=('system', 'capability'), name='unique_integration_capability')],
            },
        ),
        migrations.CreateModel(
            name='LogisticsQuoteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ENVIA', max_length=40)),
                ('basis', models.CharField(choices=[('CHECKOUT_ESTIMATE', 'Cotización estimada'), ('REALIZED_GUIDE', 'Costo real de guía')], max_length=24)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PARTIAL', 'Parcial'), ('MISSING', 'Dato ausente'), ('NOT_AUTHORIZED', 'No autorizado'), ('NOT_APPLICABLE', 'No aplica'), ('BLOCKED', 'Bloqueado')], max_length=24)),
                ('destination', models.JSONField(blank=True, default=dict)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('evidence_reference', models.CharField(blank=True, max_length=300)),
                ('observed_at', models.DateTimeField()),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_quotes', to='catalogo.productvariant')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
