# Generated by Django 5.2.17 on 2026-08-25 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_bulksimulationrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsquotesnapshot',
            name='external_reference_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='logisticsquotesnapshot',
            name='order_reference_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='approval_status',
            field=models.CharField(choices=[('HYPOTHESIS', 'Hipótesis editable, no aprobada'), ('APPROVED_LOCAL', 'Aprobada para simulación local')], default='HYPOTHESIS', max_length=24),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='reserve_behavior',
            field=models.CharField(choices=[('CAP', 'Tope de protección; no se suma automáticamente'), ('INCLUDED_IN_PRICE', 'Incluida en el precio propuesto')], default='CAP', max_length=24),
        ),
        migrations.CreateModel(
            name='ProviderDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=300)),
                ('source_sha256', models.CharField(max_length=64, unique=True)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('weight_rows', models.PositiveIntegerField(default=0)),
                ('dimension_rows', models.PositiveIntegerField(default=0)),
                ('inventory_rows', models.PositiveIntegerField(default=0)),
                ('audit_payload', models.JSONField(blank=True, default=dict)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_imports', to='catalogo.providerconfig')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierItemInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_external_id', models.CharField(blank=True, max_length=120)),
                ('warehouse_name', models.CharField(max_length=180)),
                ('reported_stock', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reserved_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('available_to_promise', models.DecimalField(decimal_places=3, max_digits=14)),
                ('observed_at', models.DateTimeField()),
                ('freshness_minutes', models.PositiveIntegerField(default=1440)),
                ('update_method', models.CharField(default='FILE', max_length=32)),
                ('evidence_reference', models.CharField(max_length=300)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='catalogo.providerdataimport')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='catalogo.suppliercatalogitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'import_batch', 'warehouse_external_id'), name='unique_supplier_inventory_import_warehouse')],
            },
        ),
    ]
