# Generated by Django 5.2.17 on 2026-08-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_physical_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalMeasurementImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=300)),
                ('source_sha256', models.CharField(max_length=64)),
                ('is_demo', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PREVIEW', 'Vista previa'), ('IMPORTED_LOCAL', 'Importado localmente'), ('DEMO_VALIDATED', 'Demo validado y bloqueado'), ('REVERSED', 'Revertido localmente')], default='PREVIEW', max_length=24)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('conflict_rows', models.PositiveIntegerField(default=0)),
                ('snapshot_before', models.JSONField(blank=True, default=dict)),
                ('rollback_snapshot', models.JSONField(blank=True, default=dict)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_measurement_imports', to='catalogo.providerconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalMeasurementImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('sku', models.CharField(db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('VALID', 'Válida para revisión'), ('ERROR', 'Error de fila'), ('CONFLICT', 'Conflicto'), ('IMPORTED_CONFIRMED', 'Evidencia confirmada importada'), ('DEMO_BLOCKED', 'Demo bloqueado'), ('REVERSED', 'Revertida localmente')], max_length=24)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('candidate_ids', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalogo.physicalmeasurementimportbatch')),
                ('supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_measurement_rows', to='catalogo.suppliercatalogitem')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_measurement_rows', to='catalogo.productvariant')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalMeasurementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REQUEST_PROVIDER', 'Solicitar al proveedor'), ('REGISTER_MEASUREMENT', 'Registrar medición'), ('IMPORT_FILE', 'Importar archivo')], max_length=28)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('IN_REVIEW', 'En revisión'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=16)),
                ('missing_fields', models.JSONField(default=list)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor_label', models.CharField(default='local-operator', max_length=160)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_tasks', to='catalogo.suppliercatalogitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_tasks', to='catalogo.productvariant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='physicalmeasurementimportbatch',
            constraint=models.UniqueConstraint(fields=('provider', 'source_sha256'), name='unique_physical_measurement_import'),
        ),
        migrations.AddConstraint(
            model_name='physicalmeasurementimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_physical_measurement_row'),
        ),
        migrations.AddConstraint(
            model_name='physicalmeasurementtask',
            constraint=models.UniqueConstraint(fields=('variant', 'action'), name='unique_physical_task_action'),
        ),
    ]
