# Generated by Django 5.2.17 on 2026-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_phase6_pricing_and_multwarehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(max_length=2048),
        ),
    ]
