# Generated by Django 5.2.17 on 2026-08-25 23:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_productimage_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SodimacCatalogImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=300)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('source_size_bytes', models.PositiveIntegerField(default=0)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('header_mapping', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREVIEW', 'Vista previa'), ('BLOCKED', 'Bloqueado por conflictos'), ('APPLIED_LOCAL', 'Aplicado solo localmente'), ('REVERSED', 'Revertido localmente')], default='PREVIEW', max_length=24)),
                ('is_fixture', models.BooleanField(default=False)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('conflict_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('applied_links', models.PositiveIntegerField(default=0)),
                ('rollback_payload', models.JSONField(blank=True, default=dict)),
                ('actor_label', models.CharField(default='local-operator', max_length=160)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SodimacCatalogLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_sku', models.CharField(db_index=True, max_length=160)),
                ('sodimac_sku', models.CharField(db_index=True, max_length=160)),
                ('listing_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('listing_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('UNLINKED', 'Sin vínculo'), ('LINKED_EXACT', 'Vínculo exacto'), ('AMBIGUOUS', 'Ambiguo'), ('STALE', 'Vencido'), ('NOT_FOUND', 'No encontrado'), ('NEEDS_REVIEW', 'Necesita revisión')], default='NEEDS_REVIEW', max_length=24)),
                ('source_kind', models.CharField(choices=[('CONFIRMED_BY_FILE', 'Confirmado por archivo'), ('MANUAL_DECISION', 'Decisión manual')], default='CONFIRMED_BY_FILE', max_length=32)),
                ('source_checksum', models.CharField(max_length=64)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('manual_decision', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_links', to='catalogo.sodimaccatalogimportbatch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sodimac_catalog_links', to='catalogo.productvariant')),
            ],
            options={
                'ordering': ['canonical_sku', 'sodimac_sku', 'listing_id'],
            },
        ),
        migrations.CreateModel(
            name='SodimacCatalogImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('canonical_sku', models.CharField(blank=True, max_length=160)),
                ('sodimac_sku', models.CharField(blank=True, max_length=160)),
                ('listing_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(max_length=24)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalogo.sodimaccatalogimportbatch')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sodimac_import_rows', to='catalogo.productvariant')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='catalogo.sodimaccataloglink')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='SodimacCatalogObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_class', models.CharField(choices=[('CONFIRMED_BY_FILE', 'Confirmado por archivo'), ('CONFIRMED_BY_API', 'Confirmado por API'), ('OBSERVED_PUBLIC_PAGE', 'Observado en página pública'), ('INFERRED', 'Inferido'), ('UNKNOWN', 'Desconocido')], max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('publication_state', models.CharField(default='UNKNOWN', max_length=80)),
                ('inventory_available', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('inventory_source', models.CharField(default='UNKNOWN', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('field_comparison', models.JSONField(blank=True, default=dict)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('severity', models.CharField(default='BLOCKER', max_length=16)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalogo.sodimaccataloglink')),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SodimacAuditTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'En cola'), ('COMPLETED', 'Completada'), ('BACKOFF', 'En espera'), ('MANUAL_REQUIRED', 'Revisión manual'), ('BLOCKED', 'Bloqueada')], default='QUEUED', max_length=24)),
                ('reason', models.CharField(max_length=160)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('cache_key', models.CharField(max_length=120)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_tasks', to='catalogo.sodimaccataloglink')),
                ('last_success_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='catalogo.sodimaccatalogobservation')),
            ],
            options={
                'ordering': ['-priority', 'next_attempt_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sodimaccataloglink',
            index=models.Index(fields=['status', 'active', 'last_verified_at'], name='catalogo_so_status_5becf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sodimaccataloglink',
            constraint=models.UniqueConstraint(fields=('canonical_sku', 'sodimac_sku', 'listing_id'), name='unique_sodimac_canonical_listing'),
        ),
        migrations.AddConstraint(
            model_name='sodimaccatalogobservation',
            constraint=models.UniqueConstraint(fields=('link', 'source_fingerprint'), name='unique_sodimac_observation_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='sodimacaudittask',
            constraint=models.UniqueConstraint(fields=('link', 'input_fingerprint'), name='unique_sodimac_audit_input'),
        ),
    ]
