# Generated by Django 5.2.17 on 2026-08-26 22:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_external_channel_product_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SodimacKitImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=300)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('source_size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('APPLIED_LOCAL', 'Aplicado solo localmente'), ('REVERSED', 'Revertido localmente')], default='APPLIED_LOCAL', max_length=24)),
                ('kit_count', models.PositiveIntegerField(default=0)),
                ('component_rows', models.PositiveIntegerField(default=0)),
                ('resolved_kits', models.PositiveIntegerField(default=0)),
                ('review_kits', models.PositiveIntegerField(default=0)),
                ('exact_components', models.PositiveIntegerField(default=0)),
                ('missing_components', models.PositiveIntegerField(default=0)),
                ('ambiguous_components', models.PositiveIntegerField(default=0)),
                ('rollback_payload', models.JSONField(blank=True, default=dict)),
                ('actor_label', models.CharField(default='local-operator', max_length=160)),
                ('external_writes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sodimaccatalogimportbatch',
            name='allow_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sodimaccatalogimportbatch',
            name='status',
            field=models.CharField(choices=[('PREVIEW', 'Vista previa'), ('PREVIEW_PARTIAL', 'Vista previa parcial'), ('BLOCKED', 'Bloqueado por conflictos'), ('APPLIED_LOCAL', 'Aplicado solo localmente'), ('APPLIED_PARTIAL', 'Aplicado parcialmente'), ('REVERSED', 'Revertido localmente')], default='PREVIEW', max_length=24),
        ),
        migrations.CreateModel(
            name='SodimacKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sodimac_kit_sku', models.CharField(db_index=True, max_length=160)),
                ('canonical_sku', models.CharField(blank=True, db_index=True, max_length=160)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('RESOLVED', 'Componentes resueltos'), ('PARTIAL', 'Componentes por revisar')], max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('source_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sodimac_kits', to='catalogo.productvariant')),
                ('created_by_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='catalogo.sodimackitimportbatch')),
            ],
            options={
                'ordering': ['sodimac_kit_sku'],
            },
        ),
        migrations.CreateModel(
            name='SodimacKitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('component_sku', models.CharField(db_index=True, max_length=160)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('match_status', models.CharField(choices=[('EXACT_SKU', 'SKU PAMO exacto'), ('AMBIGUOUS_SKU', 'SKU PAMO ambiguo'), ('MISSING_SHOPIFY', 'SKU PAMO ausente')], max_length=24)),
                ('candidate_variant_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sodimac_kit_components', to='catalogo.productvariant')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalogo.sodimackit')),
            ],
            options={
                'ordering': ['kit__sodimac_kit_sku', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'component_sku'), name='unique_sodimac_kit_component')],
            },
        ),
        migrations.AddIndex(
            model_name='sodimackit',
            index=models.Index(fields=['active', 'sodimac_kit_sku'], name='catalog_sod_kit_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='sodimackit',
            constraint=models.UniqueConstraint(fields=('created_by_batch', 'sodimac_kit_sku'), name='unique_sodimac_kit_per_batch'),
        ),
    ]
