# Generated by Django 5.2.17 on 2026-08-27 17:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=60, unique=True)),
                ('state', models.CharField(default='disabled_local', max_length=60)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('records_observed', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='MessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_body', models.TextField(default='Hola, {{contacto}}.\n\nEstos son los despachos pendientes de {{bodega}}:\n\n{{lista_pedidos}}\n\nAgradecemos confirmar su estado.')),
                ('followup_template_body', models.TextField(blank=True)),
                ('maximum_attempts', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessagingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pedidos.messagingconfig')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=160)),
                ('visible_id', models.CharField(db_index=True, max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('placed_at', models.DateTimeField(db_index=True)),
                ('customer_name', models.CharField(blank=True, max_length=240)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='COP', max_length=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('state', models.CharField(default='open', max_length=80)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-placed_at', '-created_at'],
                'indexes': [models.Index(fields=['channel', 'placed_at'], name='pedidos_ord_channel_36dee3_idx'), models.Index(fields=['visible_id', 'placed_at'], name='pedidos_ord_visible_77b389_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_id'), name='pedidos_order_channel_external_unique')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=160)),
                ('name', models.CharField(max_length=400)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('filters', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=180)),
                ('warehouse_name', models.CharField(blank=True, max_length=160)),
                ('warehouse_reference', models.CharField(blank=True, max_length=120)),
                ('warehouse_locked', models.BooleanField(default=False)),
                ('warehouse_assignment_source', models.CharField(default='channel', max_length=40)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=180)),
                ('tracking_url', models.URLField(blank=True, max_length=600)),
                ('tracking_source', models.CharField(blank=True, max_length=40)),
                ('logistics_state', models.CharField(choices=[('without_guide', 'Sin guía'), ('guide_without_tracking', 'Guía generada sin movimiento'), ('picked_up', 'Recogido'), ('in_transit', 'En tránsito'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('exception', 'Con novedad'), ('returned', 'Devuelto'), ('logistically_cancelled', 'Cancelado logísticamente')], db_index=True, default='without_guide', max_length=50)),
                ('carrier_state_original', models.CharField(blank=True, max_length=180)),
                ('carrier_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('carrier_cost_currency', models.CharField(blank=True, max_length=8)),
                ('carrier_cost_source', models.CharField(blank=True, max_length=80)),
                ('incident_category', models.CharField(blank=True, max_length=80)),
                ('incident_detail', models.TextField(blank=True)),
                ('customer_context', models.TextField(blank=True)),
                ('messaging_state', models.CharField(default='draft', max_length=60)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='pedidos.order')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='pedidos.warehouselocation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=80)),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('actor', models.CharField(max_length=240)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='pedidos.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pedidos/guias/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_by', models.CharField(max_length=240)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='pedidos.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='pedidos.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='pedidos.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=40)),
                ('external_event_id', models.CharField(max_length=180)),
                ('state_normalized', models.CharField(max_length=60)),
                ('state_original', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='pedidos.shipment')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_config', to='pedidos.warehouselocation'),
        ),
        migrations.CreateModel(
            name='ManualFollowup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('order_numbers', models.JSONField(default=list)),
                ('rendered_message', models.TextField()),
                ('state', models.CharField(default='prepared_manual', max_length=40)),
                ('prepared_by', models.CharField(max_length=240)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.warehouselocation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'external_id'), name='pedidos_item_order_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='savedfilter',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='pedidos_saved_filter_owner_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'order_item'), name='pedidos_shipment_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(fields=('shipment', 'source', 'external_event_id'), name='pedidos_tracking_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('order', 'external_id'), name='pedidos_shipment_order_external_unique'),
        ),
    ]
