# Generated by Django 5.2.17 on 2026-08-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_supplier_contacts_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierresponseevent',
            name='action',
            field=models.CharField(choices=[('order_received', 'Pedido recibido'), ('request_guide', 'Listo, enviar guia'), ('report_issue', 'Reportar novedad'), ('classify_issue', 'Clasificar novedad'), ('provide_issue_detail', 'Detallar novedad')], max_length=32),
        ),
        migrations.AlterField(
            model_name='messagingconfig',
            name='template_body',
            field=models.TextField(default='Hola, {{contacto}}.\n\nTienes un nuevo despacho de {{bodega}}:\n\n{{lista_pedidos}}\n\nAgradecemos confirmar su estado.'),
        ),
    ]
