# Generated by Django 5.2.17 on 2026-08-21 20:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='RD', max_length=40, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('requester_name', models.CharField(max_length=160)),
                ('requester_document', models.CharField(blank=True, max_length=40)),
                ('document_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=16)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada')], default='PENDING', max_length=16)),
                ('invoice_status', models.CharField(choices=[('PENDING_CODING', 'Pendiente de codificación'), ('READY', 'Lista para facturar'), ('INVOICING', 'Facturando'), ('INVOICED', 'Facturada'), ('ERROR', 'Error de facturación')], default='PENDING_CODING', max_length=24)),
                ('communication_status', models.CharField(choices=[('NOT_PREPARED', 'No preparada'), ('PREPARED', 'Preparada'), ('SENT', 'Enviada'), ('ERROR', 'Error')], default='NOT_PREPARED', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_remittances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='facturacion.remittance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PERSONAL_PICKUP', 'Retira personalmente'), ('CARRIER', 'Transportadora'), ('UBER', 'Uber'), ('INDRIVE', 'InDrive'), ('MESSENGER', 'Mensajería / domiciliario'), ('OTHER', 'Otro')], max_length=24)),
                ('provider_name', models.CharField(blank=True, max_length=160)),
                ('tracking_number', models.CharField(blank=True, max_length=160)),
                ('driver_name', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remittance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='facturacion.remittance')),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceInvoiceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Vista previa'), ('PENDING', 'Pendiente'), ('UNKNOWN_RESULT', 'Resultado desconocido'), ('SUCCEEDED', 'Exitosa'), ('FAILED', 'Fallida')], default='PENDING', max_length=24)),
                ('external_invoice_id', models.CharField(blank=True, max_length=160)),
                ('external_number', models.CharField(blank=True, max_length=80)),
                ('sanitized_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_attempts', to='facturacion.remittance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Cliente'), ('SUPPLIER', 'Proveedor')], max_length=16)),
                ('siigo_id', models.CharField(blank=True, max_length=120)),
                ('nit', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=180)),
                ('is_validated', models.BooleanField(default=False)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('party_type', 'nit'), name='unique_remittance_party_nit_type')],
            },
        ),
        migrations.CreateModel(
            name='RemittanceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('requires_validation', models.BooleanField(default=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='favorite', to='facturacion.remittanceparty')),
            ],
            options={
                'ordering': ['sort_order', 'party__name'],
            },
        ),
        migrations.AddField(
            model_name='remittance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_remittances', to='facturacion.remittanceparty'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_remittances', to='facturacion.remittanceparty'),
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('document', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_people', to='facturacion.remittanceparty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='remittance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='facturacion.remittancewarehouse'),
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('original_description', models.CharField(max_length=500)),
                ('usage_destination', models.CharField(blank=True, max_length=180)),
                ('supplier_sku', models.CharField(blank=True, max_length=120)),
                ('supplier_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('siigo_sku', models.CharField(blank=True, max_length=120)),
                ('invoice_description', models.CharField(blank=True, max_length=500)),
                ('invoice_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=500)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='facturacion.remittance')),
            ],
            options={
                'ordering': ['line_number'],
                'constraints': [models.UniqueConstraint(fields=('remittance', 'line_number'), name='unique_remittance_line_number')],
            },
        ),
    ]
