# Generated by Django 5.2.17 on 2026-10-02 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_marketplace_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('creando', 'Creando'), ('creada', 'Creada'), ('error', 'Error')], max_length=20)),
                ('customer_identification', models.CharField(max_length=32)),
                ('customer_name', models.CharField(max_length=255)),
                ('purchase_order_number', models.CharField(blank=True, max_length=64)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reteiva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reteica', models.DecimalField(decimal_places=2, max_digits=14)),
                ('retefuente', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stamped', models.BooleanField()),
                ('siigo_id', models.CharField(blank=True, max_length=64)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('siigo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('siigo_calculated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_date', models.DateField()),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.marketplaceorder')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
