# Generated by Django 5.2.17 on 2026-10-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_mercadolibretoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siigotoken',
            name='token',
            field=models.TextField(),
        ),
    ]
