# Generated by Django 5.2.17 on 2026-09-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('falabella', 'Falabella')], max_length=20)),
                ('marketplace_order_id', models.CharField(max_length=64)),
                ('marketplace_order_number', models.CharField(blank=True, max_length=64)),
                ('customer_identification', models.CharField(blank=True, max_length=32)),
                ('customer_first_name', models.CharField(blank=True, max_length=150)),
                ('customer_last_name', models.CharField(blank=True, max_length=150)),
                ('customer_email', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('error_creando_cliente', 'Error al crear cliente'), ('error_creando_orden', 'Error al crear orden'), ('orden_creada', 'Orden creada')], default='pending', max_length=30)),
                ('error_description', models.TextField(blank=True)),
                ('shopify_customer_id', models.CharField(blank=True, max_length=32)),
                ('shopify_order_id', models.CharField(blank=True, max_length=32)),
                ('shopify_order_name', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de marketplace',
                'verbose_name_plural': 'Pedidos de marketplace',
                'constraints': [models.UniqueConstraint(fields=('marketplace', 'marketplace_order_id'), name='unique_marketplace_order')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_sku', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.CharField(blank=True, max_length=32)),
                ('shopify_variant_id', models.CharField(blank=True, max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.marketplaceorder')),
            ],
            options={
                'verbose_name': 'Ítem de pedido de marketplace',
                'verbose_name_plural': 'Ítems de pedido de marketplace',
            },
        ),
    ]
