# Generated by Django 5.2.17 on 2026-09-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
