# Generated by Django 5.2.17 on 2026-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_buyer_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='fulfillment_location_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='fulfillment_location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='fulfillment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='fulfillment_status',
            field=models.CharField(blank=True, choices=[('', 'Sin evaluar'), ('asignada', 'Bodega asignada'), ('novedad', 'Novedad'), ('resuelta_manual', 'Resuelta manualmente')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplaceorderitem',
            name='inventory_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
