# Generated by Django 5.2.17 on 2026-09-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_fulfillment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_identification_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_type',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='marketplace',
            field=models.CharField(choices=[('falabella', 'Falabella'), ('mercadolibre', 'Mercado Libre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('procesando', 'Procesando'), ('error_creando_cliente', 'Error al crear cliente'), ('error_creando_orden', 'Error al crear orden'), ('orden_creada', 'Orden creada')], default='pending', max_length=30),
        ),
    ]
