# Generated by Django 5.2.17 on 2026-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_seed_mercadolibre_process_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='marketplace',
            field=models.CharField(choices=[('falabella', 'Falabella'), ('mercadolibre', 'Mercado Libre'), ('madecentro', 'Madecentro')], max_length=20),
        ),
    ]
