# Generated by Django 5.2.17 on 2026-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_seed_madecentro_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='marketplace',
            field=models.CharField(choices=[('falabella', 'Falabella'), ('mercadolibre', 'Mercado Libre'), ('madecentro', 'Madecentro'), ('sodimac', 'Sodimac')], max_length=20),
        ),
    ]
