# Generated by Django 5.2.17 on 2026-10-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_marketplaceorder_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='marketplace_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='marketplace_status',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
