# Generated by Django 5.2.17 on 2026-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_seed_sodimac_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='shopify_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
