# Generated by Django 5.2.17 on 2026-10-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_shopify_order_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('shopify_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('financial_status', models.CharField(blank=True, max_length=40)),
                ('fulfillment_status', models.CharField(blank=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('marketplace', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('customer_id', models.CharField(blank=True, max_length=32)),
                ('customer_first_name', models.CharField(blank=True, max_length=150)),
                ('customer_last_name', models.CharField(blank=True, max_length=150)),
                ('customer_identification', models.CharField(blank=True, max_length=32)),
                ('customer_city', models.CharField(blank=True, max_length=100)),
                ('customer_region', models.CharField(blank=True, max_length=100)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de Shopify',
                'verbose_name_plural': 'Pedidos de Shopify',
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrderSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de sincronización de pedidos de Shopify',
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.shopifyorder')),
            ],
            options={
                'verbose_name': 'Línea de pedido de Shopify',
                'verbose_name_plural': 'Líneas de pedido de Shopify',
                'ordering': ['position'],
            },
        ),
    ]
