# Generated by Django 5.2.17 on 2026-10-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_seed_shopify_order_process_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_location_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_api', models.BooleanField(default=False, verbose_name='Avisar por API de Envía')),
                ('notify_email', models.BooleanField(default=False, verbose_name='Avisar por correo')),
                ('notify_whatsapp', models.BooleanField(default=False, verbose_name='Avisar por WhatsApp')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Lista de correos, ej. ["bodega@ejemplo.com"].')),
                ('whatsapp_numbers', models.JSONField(blank=True, default=list, help_text='Lista en formato E.164 sin "+", ej. ["573001234567"].')),
                ('envia_warehouse_id', models.CharField(blank=True, help_text='Id de bodega de Envía Fulfillment (canal API).', max_length=16, verbose_name='Bodega en Envía')),
                ('requires_label', models.BooleanField(default=True, verbose_name='Exige guía')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bodega de despacho',
                'verbose_name_plural': 'Bodegas de despacho',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('esperando_guia', 'Esperando guía'), ('listo', 'Listo para avisar'), ('notificado', 'Bodega avisada'), ('error', 'Error al avisar'), ('manual', 'Gestión manual'), ('cancelado', 'Cancelado')], db_index=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('label_sha256', models.CharField(blank=True, max_length=64)),
                ('label_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='orders.shopifyorder')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='orders.dispatchlocation')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
            },
        ),
        migrations.CreateModel(
            name='DispatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('api', 'API de Envía'), ('email', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('error_description', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.dispatch')),
            ],
            options={
                'verbose_name': 'Aviso de despacho',
                'verbose_name_plural': 'Avisos de despacho',
                'constraints': [models.UniqueConstraint(fields=('dispatch', 'channel'), name='unique_dispatch_notification_channel')],
            },
        ),
    ]
