# Generated by Django 5.2.17 on 2026-10-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_seed_dispatch_process_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='label_carrier',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='label_service',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='label_source',
            field=models.CharField(blank=True, choices=[('canal', 'Del canal'), ('envia', 'Generada en Envía')], max_length=10),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='label_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='origin_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='origin_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='origin_province_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='origin_zip',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
