# Generated by Django 5.2.17 on 2026-10-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_dispatch_labels_and_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlocation',
            name='creates_own_label',
            field=models.BooleanField(default=False, help_text='Pedidos sin guía del canal se avisan sin guía; no se generan guías en Envía para esta bodega.', verbose_name='La bodega crea su guía'),
        ),
    ]
