# Generated by Django 5.2.17 on 2026-08-25 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceInvoiceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('UNKNOWN_RESULT', 'Resultado desconocido'), ('SUCCEEDED', 'Exitosa'), ('FAILED', 'Fallida')], default='PENDING', max_length=24)),
                ('external_invoice_id', models.CharField(blank=True, max_length=160)),
                ('external_number', models.CharField(blank=True, max_length=80)),
                ('sanitized_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_attempts', to='logistics.remittance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siigo_sku', models.CharField(blank=True, max_length=120)),
                ('invoice_description', models.CharField(blank=True, max_length=500)),
                ('invoice_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=500)),
                ('remittance_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line', to='logistics.remittanceline')),
            ],
        ),
    ]
