# Generated by Django 5.2.17 on 2026-09-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_kit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('falabella', 'Falabella'), ('mercadolibre', 'Mercado Libre'), ('madecentro', 'Madecentro'), ('sodimac', 'Sodimac')], max_length=32)),
                ('sku', models.CharField(max_length=64)),
                ('ean', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_skus', to='products.product')),
            ],
            options={
                'verbose_name': 'SKU de marketplace',
                'verbose_name_plural': 'SKUs de marketplace',
                'constraints': [models.UniqueConstraint(fields=('marketplace', 'sku'), name='unique_marketplace_sku')],
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_kits', to='products.product')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product')),
            ],
            options={
                'verbose_name': 'Componente de kit',
                'verbose_name_plural': 'Componentes de kit',
                'constraints': [models.UniqueConstraint(fields=('kit', 'component'), name='unique_kit_component'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='kit_component_quantity_gt_0')],
            },
        ),
    ]
