# Generated by Django 5.2.17 on 2026-10-02 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('falabella', 'Falabella'), ('mercadolibre', 'Mercado Libre'), ('madecentro', 'Madecentro'), ('sodimac', 'Sodimac')], max_length=32)),
                ('execution_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rows', models.JSONField()),
                ('results', models.JSONField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de SKU',
                'verbose_name_plural': 'Cargas de SKU',
                'ordering': ['-created_at'],
            },
        ),
    ]
